### ISSUE TITLE
Subscriptions example

### ISSUE THREAD

**Issue by avishail** [graphql-java-generator/GraphQL-Forum-Gradle-Tutorial-server#1]
Hi!

In your example the subscriptions query gets the board name as a parameter but doesn't use it so all in all the client will be notify on every new post regardless of what was the post's board.

Is the right solution for that is to create a different subject for each boardName, store it in a Map and return it in case it is already exist?

In addition, what would be the right way to clear resources? Say I'm holding a different Subject for every board, I would like to clean it up once the last subscriber has disconnected. Now, the class WebSocketHandler does have afterConnectionClosed function that clean Subscriptions but that doesn't affect the subjects I created and "onComplete" of the subject won't be called so I can't tell when is the right time to take the subject out of my cache. Any idea what I can do here?

Thanks!

**Comment by etienne-sf** [comment]
About the boardName:
The `PostPublisher.getPublisher(String boardName)` method returns a new Publisher for each subscription. If a boardName is provided, this method should add a filter to the returned Publisher, so that only posts from this board are returned.
Please note that I used boardName as a sample. But using an `id` should be safer.

About cleaning, yes it's a good question.
* Note that the subject is created once. You must keep it, as each Post creation is sent to this subject, whether or not there are actice subscription.
* So what's to be clean is the publishers returned `DataFetchersDelegateSubscriptionTypeImpl.subscribeToNewPost(..)`. There is one such publisher per active subscription. This is done in the generated class `WebSocketHandler`. But I didn't properly test that resources are properly cleaned. 

I will probably have to check that. And the Publisher is actually returned to the graphql-java framework. So it's up to it to free these resources.


Etienne

**Comment by etienne-sf** [comment]
Hello,

I updated the sample to add the filter on the board name. In the `org.forum.server.impl.PostPublisher`, I updated the `getPublisher` method:

```java
public class PostPublisher {

...

	@Resource
	BoardRepository boardRepository;
	@Resource
	PostRepository postRepository;
	@Resource
	TopicRepository topicRepository;

...

	Publisher<Post> getPublisher(String boardName) {
		logger.debug("Executing Subscription for {}", boardName);

		Flowable<Post> publisher = subject.toFlowable(BackpressureStrategy.BUFFER);

		if (boardName != null) {
			publisher.filter((post) -> {
				PostEntity postEntity = postRepository.findById(post.getId()).get();
				TopicEntity topicEntity = topicRepository.findById(postEntity.getTopicId()).get();
				BoardEntity boardEntity = boardRepository.findById(topicEntity.getBoardId()).get();
				return boardEntity.getName().equals(boardName);
			});
		}

		return publisher;
	}

...
}

```

Etienne
